### ISSUE TITLE
KVM+vagrant

### ISSUE THREAD

**Issue by xx-zhang** [xx-sec/xx-sec#18]
```
[root@192 ~]# cat centos7_box_kvm2/Vagrantfile 
ENV["LC_ALL"] = "en_US.UTF-8"
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "cenos7"

  config.vm.provider "libvirt" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
  SHELL

  config.vm.network :public_network, :dev => "br0", :mode => "bridge", :type => "bridge", :ip => "172.18.32.173"

end
```

**Comment by xx-zhang** [comment]
```
设置静态IP地址

sudo vim /etc/network/interfaces

# The primary network interface  
auto eth0  #表示让网卡开机自动挂载eth0
iface eth0 inet static  
address 10.0.2.15 
gateway 10.0.2.1 
netmask 255.255.255.0  


重启网络服务
sudo /etc/init.d/networking restart 

sudo ifdown eth0 && sudo ifup eth0

（ifconfig down eth0 : ifconfig up eth0）

```

**Comment by xx-zhang** [comment]
![image](https://user-images.githubusercontent.com/47806549/68071627-0bc7d980-fdb7-11e9-97c0-971a6b4386a1.png)

**Comment by xx-zhang** [comment]
```
root@ub1804:~# cat /etc/netplan/50-cloud-init.yaml
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    version: 2
    renderer: networkd
    ethernets:
        ens3:
            addresses: [172.18.32.175/24]
            gateway4: [172.18.32.1]
        nameservers:
            addresses: [114.114.114.114]
            dhcp4: false
            optional: ture
```
